### PR TITLE
Create BMI calculator, Convert meter to other and Update README

### PR DESCRIPTION
**Pull request by shin-iji**

### CODE REVIEW

**Comment by soumilk** [comment]
@shin-iji please mention that BMI here is Body mass index, and as I can see that the units of weight and height are not mentioned in the code. In actual BMI the height is in cm and weight is in kg. Correct it and PR is good to go.

**Comment by shin-iji** [comment]
@soumilk Thank you for comment. I update my code and add units of weight and height. I also update README too.

**Comment by soumilk** [comment]
@shin-iji , good to know that you are actively contributing but this is time to make your project look and function better. I am suggesting you some changes in the project 👍
1. Change the headline label to "change meter to another unit", make it bold and so that it look like a heading of the program.
2. Leave some space between the headline label and "Meter :" Label.
3. Make GUI look bigger, introduce spaces between different lines, fix the size of the tkinter frame. want to get an idea about it then visit this and run this code [CODE](https://github.com/soumilk/Python-GUI/blob/master/Projects/03-TABLE!!%20game.py).
4. Approximate all the results value upto 3 decimal places.
5. Fix the geometry of the tkinter window i.e. make it non resizable ( tk.geometry(a X b) ), search on net about how to fix the geometry of the window.
6. Modify the appreance of the buttons, see the projects already present in the repository and learn how their attributes have been modified.
7. Comment out your code properly, explain its functioning flow so that every new learner can understand it.

NOTE
THIS IS IMPORTANT, as I can see that you are making a PR directly from your master branch so insead of the recent changes, its showing me the 6 commits, I hope you also observed that. So this happnes because you are directly making commits in master branch and then making PR as its your master so all the commit log comes to me in your PR. You need to make a PR from differnt branch. 

After changes done properly, this PR is good to go

**Comment by shin-iji** [comment]
Thank you @soumilk  for your suggestions. This is my first time on Python GUI so I don't know what to do that much (I also new with PR too). And here you go.

Thanks again for this good repository. 😊

**Pull request merged**
